#!/bin/bash
#
# Install baseline coding environment for Ubuntu (20+). Kinda/sorta spec-ing out my preferred
# containerized environment.

sudo apt -y update
# Grab Zsh shell
sudo apt install -y zsh
# Install most recent Python and Node runtimes.
sudo apt install -y python3 python3-pip
sudo apt install -y nodejs npm
# TODO:  Install common global Python and Node packages
# python3 -m pip install -r requirments.txt --user
# npm i index.json
# TODO:  Install hyper and edit .hyper.js config.
cd ~/Downloads
wget https://releases.hyper.is/download/deb
sudo apt install ./hyper_*_amd64.deb
cd ~
mkdir Workspace
git clone https://github.com/lkgwbr/config.git
ln -s ~/config/.hyper.js ~/.hyper.js
# TODO:  Update .zshrc and snag ~/bin scripts.
# Install tmux (with .tmux.conf), vim (with .vimrc), and vscode (with settings.json).
sudo apt install -y tmux vim
sudo snap install --classic code
# cp ~/config/settings.json ...
# Install Hack font.
sudo apt install -y fonts-hack-ttf
# TODO:  Omic installation scripts (requiring authentication).
