#!/bin/bash
sudo apt install -y zsh
# TODO:  Install hyper and edit .hyper.js config.
# TODO:  Update .zshrc and snag ~/bin scripts.
# TODO:  Install tmux, vim, and vscode (with settings.json).
# Install Hack font.
sudo apt install -y fonts-hack-ttf
